version: "3.1"

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_parser